debug: false
server:
  port: 5050
spring:
  profiles:
    active: prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.100.10.67/easyoffice?useUnicode=true&characterEncoding=utf8
    username: root
    password: root

shiro:
  loginUrl: ${frontend.baseUrl}/login.html
  unauthorizedUrl: ${frontend.baseUrl}/unauth.html
